### ISSUE TITLE
Support for envoy Request Mirror Policies

### ISSUE THREAD

**Issue by mattiaforc** [cilium/proxy#1092]
Hi everyone, I've been experimenting with `CiliumEnvoyConfig` and I was trying to mirror traffic directed to a service to another one (for testing purposes). 
I've tried different things but none of them worked. I am now wondering if it is supported; if not, what would be the necessary steps to enable it and rebuild the proxy? Would it be something that could interest others and be officially supported, or should I try to make it work in another way?

This is the snippet of my CEC:
```yaml
virtual_hosts:
    - domains:
      - '*'
      name: lb_route
      routes:
      - match:
          prefix: /
        route:
          request_mirror_policies:
          - cluster: namespace/another-service
            runtime_fraction: 100
          weighted_clusters:
            clusters:
            - name: namespace/main-service
              weight: 100
```
I don't see any relevant logs nor error, it's simply not mirroring the traffic.  

Cilum envoy image is `quay.io/cilium/cilium-envoy:v1.27.4`

Thanks so much for any help and advice
