### ISSUE TITLE
Cilium Envoy extension fluentd access log is not able to find cluster

### ISSUE THREAD

**Issue by Raj-prateek** [cilium/proxy#1275]
Hello 👋🏽 

We are trying to push logs in a dedicated CEC configuration to fluentd using FluentdAccess log extension.
All the configuration looks good on compilation on cilium level i am getting error that is cluster not found.

## Listener Configuration:

```
 - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: listener
      filterChains:
          filters:
            - name: envoy.filters.network.http_connection_manager
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                commonHttpProtocolOptions:
                  maxStreamDuration: 0s
                access_log:
                  - name: envoy.access_loggers.fluentd
                    typedConfig:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig
                      cluster: "fluentd-forwarder"
                      stat_prefix: "access_log_fluentd"
                      tag: "envoy.access"
                      buffer_size_bytes: 16384 # 16KB buffer

```

## Cluster Definition:
```
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: "fluentd-forwarder"
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      type: LOGICAL_DNS
      load_assignment:
        cluster_name: "fluentd-forwarder"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: fluentd-forwarder.fluentd-forwarder.svc.cluster.local
                      port_value: 5000
                load_balancing_weight: 100

```

NOTE: Cluster is also defined in the same namespace.
